name: Release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  Build-and-upload:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ccecho-$${{github.ref_name}}.exe
        path: ${{github.workspace}}\.bin\${{env.BUILD_TYPE}}\ccecho.exe
  
  Release:
    runs-on: windows-latest
    needs: Build-and-upload
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ccecho-$${{github.ref_name}}.exe
